#dubbo:
#  application:
#    name: ${spring.application.name}
#    port: ${random.int[1024,65536]}
#  provider:
#    timeout: 5000
#    retries: 3
#  protocols:
#    - {port: '${random.int[1024,65536]}',name: dubbo}
#  registries:
#    - {id: registry,address: 'zookeeper://127.0.0.1:2181',timeout: 5000,register: true}
#  consumer:
#    check: false

spring:
  data:
    elasticsearch:
      cluster-name: 'my-application'
      repositories:
        enabled: true
      cluster-nodes: '124.161.95.46:9300'
#  redis:
#    port: 6379
#    password: redis-test.
#    host: 124.161.95.46
#    lettuce:
#      pool:
#        max-active: 1000
#        min-idle: 10