dubbo:
  application:
    name: ${spring.application.name}
    port: ${random.int[1024,65536]}
  provider:
    timeout: 5000
    retries: 3
  protocols:
    - {port: '${random.int[1024,65536]}',name: dubbo}
  registries:
    - {id: registry,address: 'zookeeper://127.0.0.1:2181',timeout: 5000,register: true}
  consumer:
    check: false

